apiVersion: apps/v1
kind: Deployment
metadata:
  name: eksapp-deployment
  labels:
    app: eksapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eksapp
  template:
    metadata:
      labels:
        app: eksapp
    spec:
      containers:
      - name: eksapp
        image: 339712920725.dkr.ecr.us-east-2.amazonaws.com/baar/eksapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m"